### ISSUE TITLE
產品資料 -> 進階 -> 購買備註. 填寫後商品頁未顯示

### ISSUE THREAD

**Issue by carpassion** [wuboy0307/iamplay#10]
測試於商品: Garmin 6495R 行車紀錄器

**Comment by wuboy0307** [comment]
不應該使用這個來填寫額外資訊

**Comment by carpassion** [comment]
用這個也是你叫我用的, 不然用什麼?


*__*

*張嘉倫 / Jack Chang*
*商品部 - 業務經理*
*CarPlay **愛車趣*
*行動電話 :  0986 806 777*

*公司電話 :  (02) 2795 6366*
*電子郵件 :  jack@carplay.com.tw <jack@carplay.com.tw>*
*公司地址 :  台北市內湖區安康路 28-5 號 9 樓*


*                               www.carplay.com.tw
<http://www.carplay.com.tw>*

2016-12-14 10:02 GMT+08:00 wuboy <notifications@github.com>:
