### ISSUE TITLE
商品顏色選項

### ISSUE THREAD

**Issue by carpassion** [wuboy0307/iamplay#14]
我們昨天收到第一批團購的商品資訊, 是車充和iPhone充電線. 車充有兩個顏色, 充電線有四個. 可以製作顏色的Drop Down Menu嗎?

車充顏色: 幻夜黑, 亮白銀
充電線顏色: 璀璨金, 玫瑰金, 皎潔銀, 魅惑灰

**Comment by wuboy0307** [comment]
這個就是需要用到屬性的地方 
https://www.youtube.com/watch?v=VkK6OokHYjQ
