### ISSUE TITLE
每檔圖右上促銷圖示可變更: 已售完. 熱賣. 預告

### ISSUE THREAD

**Issue by double116** [wuboy0307/iamplay#7]
開會時Ernest已查詢需24美金, Andy授權購買, 尚需另外測試

**Comment by wuboy0307** [comment]
請參考這個外掛的使用方式
http://iamplay.com.tw/wp-content/plugins/gema75_woocommerce_badges/docs/

<img width="348" alt="2016-12-12 5 33 49" src="https://cloud.githubusercontent.com/assets/2128976/21094279/3797e7d2-c091-11e6-8ef6-e9ac50b362ac.png">
<img width="494" alt="2016-12-12 5 33 56" src="https://cloud.githubusercontent.com/assets/2128976/21094280/3797f02e-c091-11e6-9e50-fe021d1b8981.png">
